sudo: false

language: erlang

otp_release:
  - 21.1

addons:
  apt:
    packages:
    - dbus
    - libdbus-1-3
    - libdbus-1-dev

cache:
  directories:
  - $HOME/.cache/rebar3

script: ./rebar3 as test do ct --verbose && ./rebar3 dialyzer && ./rebar3 xref
